
[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 1

[window.padding]
x = 8
y = 8

[general]
live_config_reload = true
import = ["/home/arie/.config/alacritty/colors.toml"]
